[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

# Redirect all routes to index.html (if later you add client-side routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
